//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelInfo
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string CalculatedDistance { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserVehicle UserVehicle { get; set; }
    }
}
