//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleData.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserVehicle()
        {
            this.TravelInfoes = new HashSet<TravelInfo>();
        }

        public int ID { get; set; }

        [Required(ErrorMessage = "User ID is required.")]
        public int? UserId { get; set; }

        [Required(ErrorMessage = "Vehicle model is required.")]
        public string VehicleModel { get; set; }

        [Required(ErrorMessage = "Vehicle make is required.")]
        public string VehicleMake { get; set; }

        [Required(ErrorMessage = "Certified mileage is required.")]
        public string CertifiedMileage { get; set; }

        [Required(ErrorMessage = "Year of manufacturing is required.")]
        [Range(1900, int.MaxValue, ErrorMessage = "Year of manufacturing must be greater than 1900.")]
        public int? YearOfManufacturing { get; set; }

        [Required(ErrorMessage = "Year of purchase is required.")]
        [Range(1900, int.MaxValue, ErrorMessage = "Year of purchase must be greater than 1900.")]
        public int? YearOfPurchase { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelInfo> TravelInfoes { get; set; }
        public virtual User User { get; set; }
    }
}
